<template>
  <main class="promotion-page">
    <PlatformFeeSubnav />
    <header class="promotion-page-head"><div><p class="eyebrow">Giảm phí có kiểm soát</p><h1>Ưu đãi phí nền tảng</h1><p>Ưu đãi chỉ áp dụng cho kỳ mới, có phạm vi, số lượt và ngân sách rõ ràng; không tạo “credit” có thể rút.</p></div><button class="btn primary" type="button" @click="openForm()"><AppIcon name="plus" size="18" /> Tạo ưu đãi nháp</button></header>
    <section class="list-card">
      <div class="filters"><label class="search"><AppIcon name="search" size="17" /><input v-model.trim="filters.q" placeholder="Tìm mã hoặc tên ưu đãi" @keyup.enter="load" /></label><select v-model="filters.status" @change="load"><option value="">Tất cả trạng thái</option><option value="draft">Nháp</option><option value="active">Đã công bố</option><option value="inactive">Ngừng áp dụng</option></select><button class="btn secondary" @click="load">Lọc</button></div>
      <div v-if="loading" class="state">Đang tải ưu đãi...</div><div v-else-if="items.length === 0" class="state"><strong>Chưa có ưu đãi phù hợp</strong></div>
      <div v-else class="table-wrap"><table><thead><tr><th>Ưu đãi</th><th>Mức giảm</th><th>Thời hạn</th><th>Phạm vi</th><th>Ngân sách</th><th>Áp dụng cùng</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><strong>{{ item.name }}</strong><small>{{ item.code }}</small></td><td><strong>{{ discountLabel(item) }}</strong><small>{{ item.duration_cycles }} kỳ / cụm</small></td><td><strong>{{ date(item.starts_at) }} - {{ date(item.ends_at) }}</strong></td><td><strong>{{ item.applies_to_all_clusters ? 'Tất cả cụm sân' : `${item.assignments?.length || 0} cụm sân` }}</strong></td><td><strong>{{ item.budget_amount ? money(item.budget_amount) : 'Không giới hạn' }}</strong><small>Đã dùng {{ money(item.spent_amount) }}</small></td><td><small>Trả trước: {{ yesNo(item.stackable_with_prepay) }}</small><small>Trả chậm: {{ yesNo(item.applies_to_deferred) }}</small><small>Kỳ lẻ: {{ yesNo(item.applies_to_bridge) }}</small></td><td><span class="status" :class="item.status">{{ statusLabel(item.status) }}</span></td><td><div class="actions"><button v-if="item.status === 'draft'" class="icon-btn" title="Sửa" @click="openForm(item)"><AppIcon name="pencil" size="17" /></button><button v-if="item.status === 'draft'" class="icon-btn green" title="Công bố" @click="requestAction('publish', item)"><AppIcon name="rocket" size="17" /></button><button v-if="item.status === 'active'" class="icon-btn danger" title="Ngừng áp dụng" @click="requestAction('deactivate', item)"><AppIcon name="power" size="17" /></button><button v-if="item.status === 'draft'" class="icon-btn danger" title="Xóa nháp" @click="requestAction('remove', item)"><AppIcon name="trash" size="17" /></button></div></td></tr></tbody></table></div>
    </section>

    <Teleport to="body"><div v-if="formOpen" class="modal-backdrop" @click.self="closeForm"><form class="modal" @submit.prevent="save"><header><div><h2>{{ form.id ? 'Sửa ưu đãi nháp' : 'Tạo ưu đãi nháp' }}</h2><p>Khi đã công bố, cấu hình không thể sửa trực tiếp.</p></div><button class="close-btn" type="button" @click="closeForm"><AppIcon name="x" size="18" /></button></header><div class="modal-body">
      <div class="field-grid"><label>Mã ưu đãi <span>*</span><input v-model.trim="form.code" maxlength="50" required @input="form.code = form.code.toUpperCase()" /><em v-if="errorFor('code')">{{ errorFor('code') }}</em></label><label>Tên ưu đãi <span>*</span><input v-model.trim="form.name" minlength="3" maxlength="150" required /><em v-if="errorFor('name')">{{ errorFor('name') }}</em></label><label>Kiểu giảm <span>*</span><select v-model="form.discount_type"><option value="percent">Theo phần trăm</option><option value="fixed">Số tiền cố định</option></select></label><label>Mức giảm <span>*</span><input v-model.number="form.discount_value" type="number" min="0.01" :max="form.discount_type === 'percent' ? 100 : 999999999999" step="0.01" required /><em v-if="errorFor('discount_value')">{{ errorFor('discount_value') }}</em></label><label v-if="form.discount_type === 'percent'">Giảm tối đa (VND)<input v-model.number="form.max_discount_amount" type="number" min="1" /></label><label>Số kỳ được hưởng / cụm <span>*</span><input v-model.number="form.duration_cycles" type="number" min="1" max="36" required /></label><label>Ngày bắt đầu<input v-model="form.starts_at" type="datetime-local" /></label><label>Ngày kết thúc<input v-model="form.ends_at" type="datetime-local" /></label><label>Ngân sách tổng (VND)<input v-model.number="form.budget_amount" type="number" min="1" /><small>Để trống nếu không giới hạn ngân sách.</small></label><label class="full">Ghi chú nội bộ<textarea v-model.trim="form.notes" rows="2" maxlength="1000"></textarea></label></div>
      <fieldset><legend>Cho phép áp dụng trong trường hợp</legend><div class="checks"><label><input v-model="form.stackable_with_prepay" type="checkbox" /> Cùng giảm trả trước</label><label><input v-model="form.applies_to_deferred" type="checkbox" /> Kỳ thuộc thỏa thuận trả chậm</label><label><input v-model="form.applies_to_bridge" type="checkbox" /> Kỳ lẻ cầu nối</label></div></fieldset>
      <fieldset><legend>Phạm vi cụm sân</legend><label class="scope-all"><input v-model="form.applies_to_all_clusters" type="checkbox" /> Áp dụng cho tất cả cụm sân</label><small v-if="form.applies_to_all_clusters" class="scope-help">Phạm vi được áp dụng động cho toàn hệ thống, kể cả cụm sân được tạo sau này; không lưu danh sách hàng nghìn ID.</small><VenueClusterCombobox v-else v-model="form.venue_cluster_ids" multiple :initial-options="selectedVenueOptions" placeholder="Nhập tên cụm sân hoặc Chủ sân để thêm" /><small v-if="!form.applies_to_all_clusters" class="scope-help"><strong>{{ form.venue_cluster_ids.length }} cụm đã chọn.</strong> Dùng tìm kiếm theo máy chủ cho các trường hợp ngoại lệ; mỗi lần chỉ tải 20 kết quả phù hợp.</small><em v-if="errorFor('venue_cluster_ids')">{{ errorFor('venue_cluster_ids') }}</em></fieldset>
    </div><footer><button class="btn secondary" type="button" @click="closeForm">Hủy</button><button class="btn primary" type="submit" :disabled="busy">Lưu ưu đãi nháp</button></footer></form></div></Teleport>
    <ConfirmModal v-model="confirm.open" :title="confirm.title" :message="confirm.message" :consequence="confirm.consequence" :confirm-text="confirm.confirmText" :type="confirm.type" @confirm="runConfirmed" />
    <p v-if="toast" class="toast" :class="toastType">{{ toast }}</p>
  </main>
</template>

<script>
import AppIcon from '../../components/AppIcon.vue'; import ConfirmModal from '../../components/ConfirmModal.vue'; import PlatformFeeSubnav from '../../components/PlatformFeeSubnav.vue'; import VenueClusterCombobox from '../../components/admin/VenueClusterCombobox.vue'; import { platformFeePromotionService } from '../../services/platformFeePromotion.service.js';
const emptyForm = () => ({ id: null, code: '', name: '', discount_type: 'percent', discount_value: 0, max_discount_amount: null, duration_cycles: 1, applies_to_all_clusters: true, stackable_with_prepay: false, applies_to_deferred: false, applies_to_bridge: false, budget_amount: null, starts_at: '', ends_at: '', venue_cluster_ids: [], cycles_per_cluster: 1, notes: '' }); const emptyConfirm = () => ({ open: false, action: '', item: null, title: '', message: '', consequence: '', confirmText: 'Xác nhận', type: 'warning' });
export default { name: 'AdminPlatformFeePromotions', components: { AppIcon, ConfirmModal, PlatformFeeSubnav, VenueClusterCombobox }, data() { return { items: [], selectedVenueOptions: [], filters: { q: '', status: '' }, loading: true, busy: false, formOpen: false, form: emptyForm(), errors: {}, confirm: emptyConfirm(), toast: '', toastType: 'success' }; }, mounted() { this.load(); }, methods: {
  async load() { this.loading = true; try { this.items = await platformFeePromotionService.list(this.filters); } catch (error) { this.show(error.message || 'Không tải được ưu đãi.', 'error'); } finally { this.loading = false; } },
  openForm(item = null) { this.errors = {}; this.selectedVenueOptions = (item?.assignments || []).map((assignment) => ({ ...(assignment.venue_cluster || {}), id: assignment.venue_cluster_id })); this.form = item ? { ...emptyForm(), ...item, starts_at: this.inputDateTime(item.starts_at), ends_at: this.inputDateTime(item.ends_at), venue_cluster_ids: (item.assignments || []).map((assignment) => String(assignment.venue_cluster_id)), cycles_per_cluster: item.assignments?.[0]?.initial_cycles || item.duration_cycles } : emptyForm(); this.formOpen = true; }, closeForm() { if (!this.busy) this.formOpen = false; },
  async save() { this.busy = true; this.errors = {}; try { const payload = { ...this.form, cycles_per_cluster: this.form.duration_cycles, starts_at: this.form.starts_at || null, ends_at: this.form.ends_at || null, max_discount_amount: this.form.max_discount_amount || null, budget_amount: this.form.budget_amount || null }; const response = this.form.id ? await platformFeePromotionService.update(this.form.id, payload) : await platformFeePromotionService.create(payload); this.formOpen = false; this.show(response.message); await this.load(); } catch (error) { this.errors = error.validation?.errors || error.data?.errors || {}; this.show(error.message || 'Không lưu được ưu đãi.', 'error'); } finally { this.busy = false; } },
  requestAction(action, item) { const config = { publish: ['Công bố ưu đãi?', 'Ưu đãi sẽ tự áp dụng cho các kỳ mới trong thời gian hiệu lực.', 'Kỳ đã phát hành không được tính lại. Ngân sách và số lượt được trừ khi kỳ mới chốt.', 'Công bố', 'warning'], deactivate: ['Ngừng áp dụng ưu đãi?', 'Kỳ mới sẽ không còn được hưởng ưu đãi này.', 'Kỳ đã phát hành giữ nguyên số tiền ưu đãi đã chốt.', 'Ngừng áp dụng', 'danger'], remove: ['Xóa ưu đãi nháp?', 'Ưu đãi nháp chưa công bố sẽ bị xóa.', 'Thao tác không thể hoàn tác.', 'Xóa nháp', 'danger'] }[action]; this.confirm = { open: true, action, item, title: config[0], message: `${item.code} · ${config[1]}`, consequence: config[2], confirmText: config[3], type: config[4] }; },
  async runConfirmed() { const { action, item } = this.confirm; this.confirm = emptyConfirm(); try { const response = action === 'publish' ? await platformFeePromotionService.publish(item.id) : action === 'deactivate' ? await platformFeePromotionService.deactivate(item.id) : await platformFeePromotionService.remove(item.id); this.show(response.message); await this.load(); } catch (error) { this.show(error.message || 'Không thực hiện được thao tác.', 'error'); } },
  errorFor(field) { return this.errors[field]?.[0] || ''; }, inputDateTime(value) { return value ? new Date(value).toISOString().slice(0, 16) : ''; }, date(value) { return value ? new Date(value).toLocaleDateString('vi-VN') : 'Không giới hạn'; }, money(value) { return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value || 0); }, discountLabel(item) { return item.discount_type === 'percent' ? `${Number(item.discount_value)}%${item.max_discount_amount ? `, tối đa ${this.money(item.max_discount_amount)}` : ''}` : this.money(item.discount_value); }, yesNo(value) { return value ? 'Có' : 'Không'; }, statusLabel(status) { return ({ draft: 'Nháp', active: 'Đã công bố', inactive: 'Ngừng áp dụng' })[status] || status; }, show(message, type = 'success') { this.toast = message; this.toastType = type; setTimeout(() => { this.toast = ''; }, 4500); },
} };
</script>

<style scoped>
.promotion-page { display: grid; gap: 18px; padding: 10px; color: #17251d; }.promotion-page-head { display: flex; align-items: flex-end; justify-content: space-between; gap: 18px; }.promotion-page-head h1, .promotion-page-head p { margin: 0; }.promotion-page-head h1 { margin-top: 3px; font-size: 24px; }.promotion-page-head p:last-child { margin-top: 7px; color: #64748b; font-size: 13px; }.eyebrow { color: #15803d; font-size: 11px; letter-spacing: .08em; text-transform: uppercase; }.list-card { border: 1px solid #e2e8f0; border-radius: 10px; background: #fff; overflow: hidden; }.filters { display: grid; grid-template-columns: 1fr 200px auto; gap: 10px; padding: 14px 16px; border-bottom: 1px solid #e2e8f0; }.search { position: relative; }.search svg { position: absolute; top: 11px; left: 11px; color: #64748b; }.search input { padding-left: 37px; } input, select, textarea { width: 100%; box-sizing: border-box; border: 1px solid #cbd5e1; border-radius: 8px; padding: 9px 11px; background: #fff; font: inherit; } input, select { min-height: 40px; }.table-wrap { overflow-x: auto; } table { width: 100%; min-width: 1150px; border-collapse: collapse; } th, td { padding: 13px 14px; border-bottom: 1px solid #eef2f7; text-align: left; vertical-align: middle; } th { background: #f8fafc; color: #64748b; font-size: 11px; text-transform: uppercase; } td strong, td small { display: block; } td small { margin-top: 4px; color: #64748b; font-size: 11px; }.actions { display: flex; gap: 6px; }.icon-btn { display: grid; width: 33px; height: 33px; place-items: center; border: 1px solid #dbe3ea; border-radius: 8px; background: #fff; color: #334155; cursor: pointer; }.icon-btn.green { color: #166534; border-color: #bbf7d0; }.icon-btn.danger { color: #b91c1c; border-color: #fecaca; }.status { display: inline-flex; border-radius: 999px; padding: 4px 9px; font-size: 11px; font-weight: 600; }.status.active { color: #166534; background: #dcfce7; }.status.draft { color: #92400e; background: #fef3c7; }.status.inactive { color: #475569; background: #e2e8f0; }.state { display: grid; min-height: 220px; place-items: center; align-content: center; color: #64748b; }.btn { display: inline-flex; min-height: 40px; align-items: center; justify-content: center; gap: 7px; border: 1px solid transparent; border-radius: 8px; padding: 9px 13px; font: inherit; font-size: 13px; font-weight: 600; cursor: pointer; }.btn.primary { color: #fff; background: #16834b; }.btn.secondary { color: #334155; background: #fff; border-color: #cbd5e1; }
.modal-backdrop { position: fixed; inset: 0; z-index: 9000; display: grid; place-items: center; padding: 18px; background: rgba(15, 23, 42, .55); }.modal { width: min(860px, calc(100vw - 28px)); max-height: calc(100vh - 36px); overflow: auto; border-radius: 11px; background: #fff; }.modal header, .modal footer { display: flex; align-items: center; justify-content: space-between; gap: 14px; padding: 17px 20px; }.modal header { position: sticky; top: 0; z-index: 2; border-bottom: 1px solid #e2e8f0; background: #fff; }.modal header h2, .modal header p { margin: 0; }.modal header h2 { font-size: 18px; }.modal header p { margin-top: 5px; color: #64748b; font-size: 12px; }.modal footer { position: sticky; bottom: 0; justify-content: flex-end; border-top: 1px solid #e2e8f0; background: #f8fafc; }.close-btn { display: grid; width: 34px; height: 34px; place-items: center; border: 0; border-radius: 8px; background: #f1f5f9; cursor: pointer; }.modal-body { display: grid; gap: 18px; padding: 20px; }.field-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }.field-grid label { display: grid; gap: 6px; color: #334155; font-size: 12px; font-weight: 600; }.field-grid label > span { color: #dc2626; }.field-grid small { color: #64748b; font-weight: 400; }.full { grid-column: 1 / -1; } em { display: block; color: #dc2626; font-size: 11px; font-style: normal; } fieldset { display: grid; gap: 11px; margin: 0; padding: 14px; border: 1px solid #e2e8f0; border-radius: 9px; } legend { padding: 0 5px; color: #334155; font-size: 12px; font-weight: 600; }.checks { display: flex; flex-wrap: wrap; gap: 16px; }.checks label, .scope-all { display: flex; align-items: center; gap: 7px; color: #334155; font-size: 12px; }.checks input, .scope-all input { width: auto; min-height: 0; }.scope-help { color: #64748b; font-size: 11px; }.toast { position: fixed; right: 22px; bottom: 22px; z-index: 9500; max-width: 430px; margin: 0; border-radius: 9px; padding: 12px 15px; box-shadow: 0 8px 24px rgba(15, 23, 42, .15); background: #ecfdf5; color: #166534; }.toast.error { color: #991b1b; background: #fef2f2; }
@media (max-width: 700px) { .promotion-page-head { align-items: stretch; flex-direction: column; }.filters, .field-grid { grid-template-columns: 1fr; }.full { grid-column: auto; }.promotion-page-head .btn { width: 100%; } }

/* Keep filter controls away from the card edge and reserve a real icon gutter. */
.list-card > .filters { box-sizing: border-box; gap: 12px; padding: 16px; }
.filters > * { min-width: 0; }
.search { min-width: 0; }
.search > .app-icon { position: absolute; inset-inline-start: 13px; top: 50%; z-index: 1; color: #64748b; pointer-events: none; transform: translateY(-50%); }
.search > input { min-width: 0; padding: 9px 12px 9px 44px; }
</style>
