<template>
  <div class="client-utility-page sg-client-page">
    <PublicNavbar />
    <main class="sg-client-shell utility-shell">
      <button type="button" class="back-link" @click="$router.push({ name:'client-complaints' })"><AppIcon name="arrowLeft" :size="17" /> Khiếu nại của tôi</button>
      <section class="utility-header"><div><p class="sg-client-eyebrow">Hỗ trợ khách hàng</p><h1>Tạo khiếu nại</h1><p>Gửi đủ thông tin để SportGo hoặc chủ sân xử lý nhanh hơn.</p></div></section>
      <section class="complaint-create-layout">
        <section class="sg-client-card form-card">
          <div class="utility-card-heading"><span class="utility-card-icon"><AppIcon name="messageSquare" :size="18" /></span><div><p class="sg-client-eyebrow">Hồ sơ yêu cầu</p><h2>Thông tin cần gửi</h2><span>Điền đúng ngữ cảnh để đội ngũ hỗ trợ xử lý nhanh hơn.</span></div></div>
          <form @submit.prevent="submit">
          <label><span>Loại khiếu nại</span><select v-model="form.complaint_type"><option value="venue">Vấn đề tại cụm sân</option><option value="system">Vấn đề hệ thống/booking</option></select></label>
          <div v-if="bookingLoading" class="context-note">Đang lấy thông tin booking...</div>
          <div v-else-if="booking" class="context-note"><strong>Booking liên quan</strong><span>#{{ booking.booking_code }} · {{ booking.venueCluster?.name || booking.venue_cluster?.name || 'Cụm sân' }}</span></div>
          <p v-if="bookingError" class="field-error">{{ bookingError }}</p>
          <label v-if="form.complaint_type === 'venue'"><span>Cụm sân</span><input :value="booking?.venueCluster?.name || booking?.venue_cluster?.name || ''" type="text" placeholder="Chọn từ booking" readonly /><small>Vui lòng tạo khiếu nại từ booking có liên quan để tự điền đúng cụm sân.</small></label>
          <label><span>Nội dung <b>*</b></span><textarea v-model.trim="form.content" rows="7" maxlength="2000" placeholder="Mô tả vấn đề, thời điểm xảy ra và mong muốn được hỗ trợ..."></textarea><small>{{ form.content.length }}/2000 ký tự</small></label>
          <label><span>Ảnh minh chứng <small>Không bắt buộc · JPG, PNG hoặc WebP, tối đa 5MB</small></span><input ref="evidenceInput" type="file" accept="image/jpeg,image/png,image/webp" @change="selectEvidence" /><small v-if="evidenceFile">Đã chọn: {{ evidenceFile.name }}</small></label>
          <p v-if="error" class="field-error">{{ error }}</p>
          <div class="form-actions"><button type="button" class="sg-client-button" @click="$router.back()">Hủy</button><button type="submit" class="sg-client-button sg-client-button--primary" :disabled="submitting || !isValid"><AppIcon name="send" :size="16" /> {{ submitting ? 'Đang gửi...' : 'Gửi khiếu nại' }}</button></div>
          </form>
        </section>
        <aside class="sg-client-card utility-guide-card">
          <div class="utility-card-heading"><span class="utility-card-icon is-blue"><AppIcon name="shieldCheck" :size="18" /></span><div><p class="sg-client-eyebrow">Hướng dẫn nhanh</p><h2>Gửi yêu cầu hiệu quả</h2></div></div>
          <ol class="utility-guide-list"><li><strong>Chọn đúng booking</strong><span>Gửi từ booking liên quan để SportGo xác định sân và thời gian.</span></li><li><strong>Mô tả theo trình tự</strong><span>Nêu thời điểm, vấn đề gặp phải và mong muốn được hỗ trợ.</span></li><li><strong>Đính kèm bằng chứng</strong><span>Ảnh hoặc thông tin xác nhận giúp việc đối soát rõ ràng hơn.</span></li></ol>
          <div class="utility-guide-note"><AppIcon name="clock" :size="16" /><span>Yêu cầu mới sẽ xuất hiện trong <strong>Khiếu nại của tôi</strong> để bạn theo dõi từng phản hồi.</span></div>
          <router-link class="sg3-button sg3-button--secondary utility-guide-link" to="/bookings"><AppIcon name="calendar" :size="16" /> Chọn từ lịch đặt sân</router-link>
        </aside>
      </section>
    </main>
  </div>
</template>

<script>
import AppIcon from '../../components/AppIcon.vue';
import PublicNavbar from '../../components/PublicNavbar.vue';
import { bookingService } from '../../services/bookingService.js';
import { complaintService } from '../../services/complaintService.js';
export default { name:'ComplaintCreate', components:{ AppIcon, PublicNavbar }, data(){return {form:{complaint_type:this.$route.query.booking_id?'venue':'system',booking_id:this.$route.query.booking_id||'',venue_cluster_id:'',content:''},booking:null,bookingLoading:false,bookingError:'',error:'',submitting:false,evidenceFile:null}}, computed:{isValid(){return this.form.content.length>=10 && (this.form.complaint_type==='system' || Boolean(this.form.booking_id && this.form.venue_cluster_id))}}, mounted(){if(this.form.booking_id)this.loadBooking()}, methods:{async loadBooking(){this.bookingLoading=true;this.bookingError='';try{this.booking=await bookingService.getBooking(this.form.booking_id);this.form.venue_cluster_id=this.booking.venue_cluster_id||this.booking.venueCluster?.id||this.booking.venue_court?.venue_cluster_id||''}catch(error){this.bookingError=error.message||'Không tải được booking.'}finally{this.bookingLoading=false}},selectEvidence(event){const file=event.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){this.error='Ảnh minh chứng không được vượt quá 5MB.';event.target.value='';return}this.evidenceFile=file;this.error=''},async submit(){this.error='';if(this.form.content.length<10){this.error='Nội dung cần ít nhất 10 ký tự.';return}if(this.form.complaint_type==='venue'&&!this.form.venue_cluster_id){this.error='Cần chọn booking có cụm sân liên quan.';return}this.submitting=true;try{const payload=new FormData();Object.entries(this.form).forEach(([key,value])=>{if(value!==''&&value!==null&&value!==undefined)payload.append(key,value)});if(this.evidenceFile)payload.append('evidence_image',this.evidenceFile);const response=await complaintService.create(payload);const id=response.data?.id||response.data?.complaint?.id;if(id)this.$router.replace({name:'client-complaint-detail',params:{id}});else this.$router.replace({name:'client-complaints'})}catch(error){this.error=error.message||'Không thể gửi khiếu nại.'}finally{this.submitting=false}}}};
</script>

<style scoped>
.utility-shell{padding-top:84px;padding-bottom:64px}.back-link{display:inline-flex;align-items:center;gap:8px;border:0;background:transparent;color:#087642;font-weight:700;cursor:pointer;margin-bottom:18px}.utility-header h1{margin:8px 0}.utility-header p:last-child{margin:0;color:#64748b}.complaint-create-layout{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:20px;align-items:start}.form-card{padding:26px}.form-card form{display:grid;gap:20px}.form-card label{display:grid;gap:8px}.form-card label>span{font-weight:700}.form-card label b{color:#b42318}.form-card input,.form-card select,.form-card textarea{width:100%;box-sizing:border-box;border:1px solid #b7e6c8;border-radius:8px;padding:12px;background:#fff;color:#193027;font:inherit}.form-card textarea{resize:vertical}.form-card small{color:#64748b}.context-note{display:grid;gap:5px;padding:14px;background:#f1fbf5;border-left:3px solid #0b9b55}.field-error{margin:0;color:#b42318}.form-actions{display:flex;justify-content:flex-end;gap:12px;padding-top:6px}.utility-card-heading{display:flex;align-items:flex-start;gap:12px;margin-bottom:20px}.utility-card-heading h2{margin:3px 0 0;font-size:19px;color:#193027}.utility-card-heading>div>span{display:block;margin-top:6px;color:#64748b;font-size:12px;line-height:1.5}.utility-card-icon{display:grid;flex:0 0 38px;width:38px;height:38px;place-items:center;border-radius:11px;background:#e6f7ec;color:#087642}.utility-card-icon.is-blue{background:#eaf3ff;color:#2b69a7}.utility-guide-card{padding:22px}.utility-guide-list{display:grid;gap:17px;margin:0;padding:0;list-style:none;counter-reset:guide}.utility-guide-list li{position:relative;padding-left:34px}.utility-guide-list li::before{position:absolute;left:0;top:0;display:grid;width:24px;height:24px;place-items:center;border-radius:50%;background:#e6f7ec;color:#087642;font-size:11px;font-weight:900;counter-increment:guide;content:counter(guide)}.utility-guide-list strong,.utility-guide-list span{display:block}.utility-guide-list strong{font-size:13px;color:#193027}.utility-guide-list span{margin-top:4px;color:#64748b;font-size:12px;line-height:1.55}.utility-guide-note{display:flex;gap:8px;margin-top:22px;padding:12px;border:1px solid #d9eee1;border-radius:10px;background:#f5fbf7;color:#64748b;font-size:12px;line-height:1.5}.utility-guide-note svg{flex:none;color:#087642}.utility-guide-note strong{color:#193027}.utility-guide-link{width:100%;margin-top:15px}@media(max-width:860px){.complaint-create-layout{grid-template-columns:1fr}.utility-guide-card{order:-1}}@media(max-width:560px){.form-card,.utility-guide-card{padding:18px}.form-actions{align-items:stretch;flex-direction:column}.form-actions .sg-client-button{width:100%}}
</style>
