<template>
  <div class="client-utility-page sg-client-page">
    <PublicNavbar />
    <main class="sg-client-shell utility-shell">
      <button type="button" class="back-link" @click="$router.push({ name:'client-complaints' })"><AppIcon name="arrowLeft" :size="17" /> Khiếu nại của tôi</button>
      <section v-if="loading" class="sg-client-card utility-state"><span class="spinner"></span> Đang tải chi tiết...</section>
      <section v-else-if="error" class="sg-client-card utility-state" role="alert"><AppIcon name="alert" :size="20" /><span>{{ error }}</span><button type="button" class="sg-client-button" @click="load">Thử lại</button></section>
      <template v-else-if="complaint">
        <div class="detail-workspace">
        <section class="utility-header"><div><p class="sg-client-eyebrow">{{ typeLabel(complaint.complaint_type) }}</p><h1>Khiếu nại #{{ complaint.id }}</h1><p>{{ statusLabel(complaint.status) }} · {{ formatDate(complaint.created_at) }}</p></div><router-link v-if="complaint.booking_id || complaint.booking?.id" :to="{ name:'booking-detail', params:{ id: complaint.booking_id || complaint.booking.id } }" class="sg-client-button sg-client-button--primary"><AppIcon name="calendar" :size="16" /> Xem booking</router-link></section>
        <section class="sg-client-card complaint-detail-card"><div class="original-message"><strong>Nội dung đã gửi</strong><p>{{ complaint.content }}</p></div><div class="timeline"><article class="timeline-item"><span class="timeline-mark"></span><div><strong>Bạn đã gửi khiếu nại</strong><p>{{ complaint.content }}</p><small>{{ formatDate(complaint.created_at) }}</small></div></article><article v-for="item in timeline" :key="item.id" class="timeline-item"><span class="timeline-mark"></span><div><strong>{{ item.user?.id === complaint.customer_id ? 'Bạn' : (item.user?.full_name || 'Bộ phận hỗ trợ') }}</strong><p>{{ item.content }}</p><small>{{ formatDate(item.created_at) }}</small></div></article></div><form v-if="canReply" class="reply-form" @submit.prevent="submitReply"><label for="reply-content">Phản hồi</label><textarea id="reply-content" v-model.trim="replyContent" rows="4" maxlength="4000" placeholder="Nhập nội dung trao đổi..." :disabled="sending"></textarea><p v-if="replyError" class="field-error">{{ replyError }}</p><button type="submit" class="sg-client-button sg-client-button--primary" :disabled="sending || replyContent.length < 2"><AppIcon name="send" :size="16" /> {{ sending ? 'Đang gửi...' : 'Gửi phản hồi' }}</button></form><div v-else class="closed-note">Khiếu nại đã kết thúc, không thể gửi thêm phản hồi.</div></section>
        <aside class="sg-client-card detail-context-card">
          <div class="utility-card-heading"><span class="utility-card-icon"><AppIcon name="messageSquare" :size="18" /></span><div><p class="sg-client-eyebrow">Hồ sơ hỗ trợ</p><h2>Thông tin yêu cầu</h2></div></div>
          <div class="detail-context-status"><span>Trạng thái hiện tại</span><strong>{{ statusLabel(complaint.status) }}</strong></div>
          <dl class="detail-context-list"><div><dt>Loại yêu cầu</dt><dd>{{ typeLabel(complaint.complaint_type) }}</dd></div><div><dt>Mã booking</dt><dd>{{ complaint.booking_id ? `#${complaint.booking_id}` : 'Không gắn booking' }}</dd></div><div><dt>Ngày gửi</dt><dd>{{ formatDate(complaint.created_at) }}</dd></div></dl>
          <div class="detail-context-note"><AppIcon name="info" :size="16" /><span>Phản hồi mới nhất sẽ được thêm vào dòng thời gian bên trái.</span></div>
          <router-link v-if="complaint.booking_id || complaint.booking?.id" class="sg3-button sg3-button--secondary detail-context-action" :to="{ name:'booking-detail', params:{ id: complaint.booking_id || complaint.booking.id } }"><AppIcon name="calendar" :size="16" /> Mở booking liên quan</router-link>
        </aside>
        </div>
      </template>
    </main>
  </div>
</template>

<script>
import AppIcon from '../../components/AppIcon.vue';
import PublicNavbar from '../../components/PublicNavbar.vue';
import { complaintService } from '../../services/complaintService.js';
export default { name:'ClientComplaintDetail', components:{ AppIcon, PublicNavbar }, data(){return { complaint:null, timeline:[], loading:true, error:'', replyContent:'', replyError:'', sending:false }}, computed:{canReply(){return !['resolved','rejected','closed'].includes(this.complaint?.status)}}, mounted(){this.load()}, methods:{async load(){this.loading=true;this.error='';try{const response=await complaintService.get(this.$route.params.id);const payload=response.data||{};this.complaint=payload.complaint||null;this.timeline=payload.timeline||[]}catch(error){this.error=error.message||'Vui lòng thử lại.'}finally{this.loading=false}},async submitReply(){this.replyError='';this.sending=true;try{const response=await complaintService.reply(this.complaint.id,this.replyContent);this.timeline.push(response.data);this.replyContent='';this.complaint.status='processing'}catch(error){this.replyError=error.message||'Không thể gửi phản hồi.'}finally{this.sending=false}},typeLabel(type){return type==='venue'?'Khiếu nại cụm sân':'Khiếu nại hệ thống'},statusLabel(status){return {open:'Mới gửi',processing:'Đang xử lý',resolved:'Đã xử lý',rejected:'Từ chối',closed:'Đã đóng'}[status]||status||'Chưa cập nhật'},formatDate(value){return value?new Date(value).toLocaleString('vi-VN'):'-'}}};
</script>

<style scoped>
.utility-shell{padding-top:84px;padding-bottom:64px}.back-link{display:inline-flex;align-items:center;gap:8px;border:0;background:transparent;color:#087642;font-weight:700;cursor:pointer;margin-bottom:18px}.utility-header{display:flex;justify-content:space-between;align-items:end;gap:24px;margin-bottom:24px}.utility-header h1{margin:8px 0}.utility-header p:last-child{margin:0;color:#64748b}.utility-state{min-height:180px;display:flex;align-items:center;justify-content:center;gap:12px;color:#64748b}.detail-workspace{display:grid;grid-template-columns:minmax(0,1fr) 292px;gap:20px;align-items:start}.detail-workspace .utility-header{grid-column:1 / -1}.complaint-detail-card{padding:24px}.original-message{padding:18px;background:#f1fbf5;border-left:3px solid #0b9b55}.original-message p{margin:8px 0 0;white-space:pre-wrap}.timeline{display:grid;gap:20px;padding:24px 0}.timeline-item{display:flex;gap:14px}.timeline-mark{width:10px;height:10px;border-radius:50%;background:#0b9b55;margin-top:6px;flex:none}.timeline-item p{margin:6px 0;white-space:pre-wrap;color:#334155}.timeline-item small{color:#64748b}.reply-form{display:grid;gap:10px;border-top:1px solid #d9eee1;padding-top:20px}.reply-form label{font-weight:700}.reply-form textarea{width:100%;resize:vertical;border:1px solid #b7e6c8;border-radius:8px;padding:12px;font:inherit;box-sizing:border-box}.field-error{margin:0;color:#b42318}.closed-note{padding:14px;background:#f8fafc;color:#64748b}.detail-context-card{padding:21px}.detail-context-status{display:grid;gap:5px;padding:14px;border-radius:10px;background:#f1fbf5;color:#64748b;font-size:12px}.detail-context-status strong{color:#087642;font-size:15px}.detail-context-list{display:grid;gap:0;margin:18px 0}.detail-context-list div{display:flex;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid #edf5ef}.detail-context-list dt{color:#64748b;font-size:12px}.detail-context-list dd{margin:0;text-align:right;color:#193027;font-size:12px;font-weight:700}.detail-context-note{display:flex;gap:8px;padding:12px;border:1px solid #d9eee1;border-radius:10px;color:#64748b;font-size:12px;line-height:1.5}.detail-context-note svg{flex:none;color:#087642}.detail-context-action{width:100%;margin-top:15px}@media(max-width:820px){.detail-workspace{grid-template-columns:1fr}.detail-workspace .utility-header{grid-column:auto}.detail-context-card{order:2}}@media(max-width:720px){.utility-header{align-items:stretch;flex-direction:column}}
</style>
